name: Pylint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: macos-15

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"  # change based on what version we use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint fastapi[all] uvicorn firebase-admin

    - name: Run pylint
      run: pylint backend/ --fail-under=8.0 --disable=W0621,W0613
