# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: SwiftLint

on:
  push:
    branches: [ "main" ]
    paths:
      - 'digital-stethoscope/**'
      - '.github/workflows/swift-lint.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'digital-stethoscope/**'
      - '.github/workflows/swift-lint.yml'

jobs:
  build:

    runs-on: macos-15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Install SwiftLint
    #   run: brew install swiftlint

    - name: Resolve Swift package dependencies
      working-directory: digital-stethoscope
      run: xcodebuild -resolvePackageDependencies -project digital-stethoscope.xcodeproj

      # OR if using a workspace:
      # run: xcodebuild -resolvePackageDependencies -workspace YourWorkspaceName.xcworkspace -scheme YourSchemeName

    - name: SwiftFormat
      run: swiftformat . --lint
      
    # - name: SwiftLint
    #   run: swiftlint lint --strict

