# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: SwiftLint

on:
  push:
    branches: [ "main" ]
    paths:
      - 'digital-stethoscope/**'
      - '.github/workflows/swiftLint.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'digital-stethoscope/**'
      - '.github/workflows/swiftLint.yml'

jobs:
  lint:
    runs-on: macos-15
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Resolve Swift package dependencies
      working-directory: digital-stethoscope
      run: xcodebuild -resolvePackageDependencies -project digital-stethoscope.xcodeproj

    - name: SwiftFormat
      run: swiftformat . --lint

